# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\user\\Desktop\\Python'],
             binaries=[],
             datas=[
			 ('images/spiderman_1.png', 'images'),
			 ('images/spider_swing.png', 'images'),
			 ('images/bitcoin.png', 'images'),
			 ('images/spider_had.png', 'images'),
			 ('sounds/Panthurr - Woof Pt 1 (special version for indyuk).mp3', 'sounds'),
			 ('sounds/coinsound.mp3', 'sounds'),
			 ('images/hightscore.png','images'),
			 ('images/0.png','images'),
			 ('images/1.png','images'),
			 ('images/2.png','images'),
			 ('images/3.png','images'),
			 ('images/4.png','images'),
			 ('images/5.png','images'),
			 ('images/6.png','images'),
			 ('images/7.png','images'),
			 ('images/8.png','images'),
			 ('images/9.png','images'),
			 ('images/10.png','images'),
			 ('images/11.png','images'),
			 ('images/12.png','images'),
			 ('images/13.png','images'),
			 ('images/14.png','images'),
			 ('images/15.png','images'),
			 ('images/16.png','images'),
			 ('images/17.png','images'),
			 ('images/18.png','images'),
			 ('images/19.png','images'),
			 ('images/20.png','images'),
			 ('images/21.png','images'),
			 ('images/22.png','images'),
			 ('images/23.png','images'),
			 ('images/24.png','images'),
			 ('images/coin_1.png','images'),
			 ('images/coin_2.png','images'),
			 ('images/coin_3.png','images'),
			 ('images/coin_4.png','images'),
			 ('images/coin_5.png','images'),
			 ('images/coin_6.png','images'),
			 ('images/spiderman_fall.png','images'),
			 ('images/window.png','images'),
			 ('images/window_2.png','images'),
			 ('images/window_3.png','images'),
			 ('images/magmablock.jpg','images'),
			 ('images/spiderman_right_2.png','images'),
			 ('images/spiderman_right_3.png','images'),
			 ('images/spiderman_right_4.png','images'),
			 ('images/spiderman_left_2.png','images'),
			 ('images/spiderman_left_3.png','images'),
			 ('images/spiderman_left_4.png','images'),
			 ('images/wallpaper.jpg','images'),
			 ('fonts/dpcomic.ttf','fonts'),
			 ('images/background_2.png','images'),
			 ('fonts/karma.otf','fonts'),
			 ('fonts/PressStart2P-Regular.ttf','fonts'),
			 ('fonts/font.otf','fonts'),
			 ('fonts/Thirteen-Pixel-Fonts.ttf','fonts'),
			 ('fonts/papercut.ttf','fonts'),
			 ('fonts/ka1.ttf','fonts')
			 ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='name',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False ,icon='spiderman.ico')
